//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface Activity {
    id: number;
    subject: string | undefined;
    notes: string | undefined;
    activityType: number | undefined;
    scheduledAt: Date | undefined;
    createdAt: Date | undefined;
    createdByUserId: number | undefined;
    activityState: number | undefined;
    assignedToUserId: number | undefined;
    relatedEntityName: string | undefined;
    relatedEntityId: number | undefined;
    customerContactPersonId: number | undefined;
    assignedToUser: Users;
    createdByUser: Users;
    customerContactPerson: CompanyPerson;
}

export interface ActivityDto {
    subject: string | undefined;
    notes: string | undefined;
    activityType: ActivityType;
    scheduledAt: Date | undefined;
    relatedEntityName: string | undefined;
    relatedEntityId: number | undefined;
    activityState: ActivityState;
    assignedToUserId: number | undefined;
    customerContactPersonId: number | undefined;
    id: number;
}

export interface ActivityDtoForInsertion {
    subject: string | undefined;
    notes: string | undefined;
    activityType: ActivityType;
    scheduledAt: Date | undefined;
    relatedEntityName: string | undefined;
    relatedEntityId: number | undefined;
    activityState: ActivityState;
    assignedToUserId: number | undefined;
    customerContactPersonId: number | undefined;
}

export interface ActivityDtoForUpdate {
    subject: string | undefined;
    notes: string | undefined;
    activityType: ActivityType;
    scheduledAt: Date | undefined;
    relatedEntityName: string | undefined;
    relatedEntityId: number | undefined;
    activityState: ActivityState;
    assignedToUserId: number | undefined;
    customerContactPersonId: number | undefined;
    id: number;
}

export interface ActivityDtoIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: ActivityDto[] | undefined;
    isSuccess: boolean;
}

export enum ActivityState {
    Planned = 0,
    InProgress = 1,
    Completed = 2,
    Canceled = 3,
    Postponed = 4,
    Failed = 5,
}

export enum ActivityType {
    Task = 0,
    Call = 1,
    Email = 2,
    Meeting = 3,
    Activity = 4,
    Visiting = 5,
    Other = 6,
}

export interface AnswerDto {
    questionId: number;
    optionId: number | undefined;
    textAnswer: string | undefined;
    optionDescription: string | undefined;
}

export interface AssignToStateDto {
    educationId: number;
    state: PersonelEgitimDurumlari;
}

export interface BoardDto {
    name: string;
    description: string | undefined;
    id: number;
}

export interface BoardViewDto {
    id: number;
    name: string | undefined;
    type: string | undefined;
    order: number;
    settingsJson: string | undefined;
}

export interface CalendarEvent {
    id: number;
    title: string | undefined;
    startDate: Date | undefined;
    endDate: Date | undefined;
    allDay: boolean | undefined;
    eventType: number | undefined;
    releatedName: string | undefined;
    releatedId: number | undefined;
    assignedId: number | undefined;
    status: number | undefined;
    priority: number | undefined;
    createdBy: number | undefined;
    createdAt: Date | undefined;
    assigned: Users;
    createdByNavigation: Users;
}

export interface CashAccount {
    id: number;
    cashCode: string | undefined;
    cashName: string | undefined;
    description: string | undefined;
    currencyId: number;
    specialCode: string | undefined;
    isPassive: boolean;
    createdAt: Date;
    createdBy: number;
    updatedAt: Date;
    updatedBy: number;
    createdByNavigation: Users;
    currency: Currency;
    updatedByNavigation: Users;
}

export interface CashAccountDto {
    cashName: string | undefined;
    description: string | undefined;
    currencyId: number;
    specialCode: string | undefined;
    isPassive: boolean;
    id: number;
    cashCode: string | undefined;
    currencyCode: string | undefined;
}

export interface CashAccountDtoForInsertion {
    cashName: string | undefined;
    description: string | undefined;
    currencyId: number;
    specialCode: string | undefined;
    isPassive: boolean;
    cashCode: string | undefined;
    createdBy: number | undefined;
    updatedBy: number | undefined;
}

export interface CashAccountDtoForUpdate {
    cashName: string | undefined;
    description: string | undefined;
    currencyId: number;
    specialCode: string | undefined;
    isPassive: boolean;
}

export interface CashAccountDtoIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: CashAccountDto[] | undefined;
    isSuccess: boolean;
}

export interface ColumnDto {
    id: number;
    title: string | undefined;
    type: ColumnType;
    boardId: number;
    order: number;
    settings: string | undefined;
}

export enum ColumnType {
    Text = 0,
    Status = 1,
    Date = 2,
    Person = 3,
    Timeline = 4,
    Document = 5,
    Dependency = 6,
}

export interface Company {
    id: number;
    firma: string | undefined;
    yetkili: string | undefined;
    adres: string | undefined;
    email: string | undefined;
    telefon: string | undefined;
    turu: string | undefined;
    "tedarikciPuanı": number | undefined;
    tedarikciSinifi: string | undefined;
    calismaBaslamaTarihi: DateOnly;
    degerlendirmeTarihi: DateOnly;
    sektor: string | undefined;
    referans: string | undefined;
    onayDurumu: string | undefined;
    isActive: boolean | undefined;
    sirketTuru: number | undefined;
    ulkeAdi: string | undefined;
    vergiNumarasi: string | undefined;
    opportunity: Opportunity[] | undefined;
    purchaseOrders: PurchaseOrders[] | undefined;
}

export interface CompanyPerson {
    id: number;
    yetkiliKisi: string | undefined;
    gorevi: string | undefined;
    tel: string | undefined;
    eposta: string | undefined;
    firma_Id: number | undefined;
    isActive: boolean | undefined;
    activity: Activity[] | undefined;
    opportunity: Opportunity[] | undefined;
}

export interface Contracts {
    id: number;
    kurum: string | undefined;
    sirket: string | undefined;
    sozlesmeTarihi: DateOnly;
    sozlesmeNo: string | undefined;
    sozlesmeAdi: string | undefined;
    nsnKodu: string | undefined;
    urunAdi: string | undefined;
    adet: number | undefined;
    birimFiyat: number | undefined;
    tutar: number | undefined;
    teslimGunu: string | undefined;
    teslimTarihi: DateOnly;
    durum: string | undefined;
    aciklama: string | undefined;
    isActive: boolean | undefined;
    priceOfferId: number | undefined;
    sozlesmeBaslangicTarihi: DateOnly;
    sozlesmeBitisTarihi: DateOnly;
    purchaseOrdersId: number | undefined;
    priceOffer: PriceOffer;
    purchaseOrders: PurchaseOrders;
}

export interface ContractsDto {
    kurum: string | undefined;
    sirket: string | undefined;
    sozlesmeTarihi: DateOnly;
    sozlesmeNo: string | undefined;
    sozlesmeAdi: string | undefined;
    nsnKodu: string | undefined;
    urunAdi: string | undefined;
    adet: number | undefined;
    birimFiyat: number | undefined;
    tutar: number | undefined;
    teslimGunu: string | undefined;
    teslimTarihi: DateOnly;
    durum: string | undefined;
    aciklama: string | undefined;
    priceOfferId: number | undefined;
    purchaseOrdersId: number | undefined;
    sozlesmeBaslangicTarihi: DateOnly;
    sozlesmeBitisTarihi: DateOnly;
    id: number;
}

export interface ContractsDtoForInsertion {
    kurum: string | undefined;
    sirket: string | undefined;
    sozlesmeTarihi: DateOnly;
    sozlesmeNo: string | undefined;
    sozlesmeAdi: string | undefined;
    nsnKodu: string | undefined;
    urunAdi: string | undefined;
    adet: number | undefined;
    birimFiyat: number | undefined;
    tutar: number | undefined;
    teslimGunu: string | undefined;
    teslimTarihi: DateOnly;
    durum: string | undefined;
    aciklama: string | undefined;
    priceOfferId: number | undefined;
    purchaseOrdersId: number | undefined;
    sozlesmeBaslangicTarihi: DateOnly;
    sozlesmeBitisTarihi: DateOnly;
    isActive: boolean | undefined;
}

export interface ContractsDtoForUpdate {
    kurum: string | undefined;
    sirket: string | undefined;
    sozlesmeTarihi: DateOnly;
    sozlesmeNo: string | undefined;
    sozlesmeAdi: string | undefined;
    nsnKodu: string | undefined;
    urunAdi: string | undefined;
    adet: number | undefined;
    birimFiyat: number | undefined;
    tutar: number | undefined;
    teslimGunu: string | undefined;
    teslimTarihi: DateOnly;
    durum: string | undefined;
    aciklama: string | undefined;
    priceOfferId: number | undefined;
    purchaseOrdersId: number | undefined;
    sozlesmeBaslangicTarihi: DateOnly;
    sozlesmeBitisTarihi: DateOnly;
}

export interface ContractsDtoIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: ContractsDto[] | undefined;
    isSuccess: boolean;
}

export interface CreateBoardDto {
    name: string;
    description: string | undefined;
}

export interface CreateBoardViewDto {
    name: string;
    type: string;
    settingsJson: string | undefined;
}

export interface CreateColumnDto {
    title: string;
    type: ColumnType;
    settings: string | undefined;
}

export interface CreateGroupDto {
    title: string;
    color: string | undefined;
    position: string | undefined;
}

export interface CreateItemDto {
    name: string;
    groupId: number;
    parentItemId: number | undefined;
}

export interface CreateOptionDto {
    text: string | undefined;
    puan: number | undefined;
}

export interface CreateQuestionDto {
    text: string | undefined;
    type: QuestionType;
}

export interface CreateQuestionGroupDto {
    name: string | undefined;
    surveyOption: CreateOptionDto[] | undefined;
    surveyQuestion: CreateQuestionDto[] | undefined;
    inverseParentGroup: CreateQuestionGroupDto[] | undefined;
}

export interface CreateSurveyDto {
    title: string | undefined;
    description: string | undefined;
    surveyType: SurveyType;
    surveyQuestionGroup: CreateQuestionGroupDto[] | undefined;
    puanIsShow: boolean | undefined;
}

export interface Currency {
    id: number;
    createdAt: Date;
    currencyName: string | undefined;
    symbol: string | undefined;
    isPassive: boolean;
    pennyName: string | undefined;
    currencyCode: string | undefined;
    cashAccount: CashAccount[] | undefined;
}

export interface CurrencyDto {
    currencyName: string | undefined;
    symbol: string | undefined;
    pennyName: string | undefined;
    currencyCode: string | undefined;
    id: number;
    createdAt: Date;
}

export interface CurrencyDtoForInsertion {
    currencyName: string | undefined;
    symbol: string | undefined;
    pennyName: string | undefined;
    currencyCode: string | undefined;
}

export interface CurrencyDtoForUpdate {
    currencyName: string | undefined;
    symbol: string | undefined;
    pennyName: string | undefined;
    currencyCode: string | undefined;
}

export interface CurrencyDtoIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: CurrencyDto[] | undefined;
    isSuccess: boolean;
}

export interface CustomerContactDto {
    id: number;
    yetkiliKisi: string | undefined;
    gorevi: string | undefined;
    tel: string | undefined;
    eposta: string | undefined;
    firma_Id: number | undefined;
    isActive: boolean | undefined;
}

export interface CustomerDto {
    firma: string | undefined;
    yetkili: string | undefined;
    adres: string | undefined;
    email: string | undefined;
    telefon: string | undefined;
    turu: string | undefined;
    "tedarikciPuanı": number | undefined;
    tedarikciSinifi: string | undefined;
    calismaBaslamaTarihi: DateOnly;
    degerlendirmeTarihi: DateOnly;
    sektor: string | undefined;
    referans: string | undefined;
    sirketTuru: CustomerType;
    ulkeAdi: string | undefined;
    vergiNumarasi: string | undefined;
    id: number;
    contacts: CustomerContactDto[] | undefined;
    onayDurumu: string | undefined;
}

export interface CustomerDtoForInsertion {
    firma: string | undefined;
    yetkili: string | undefined;
    adres: string | undefined;
    email: string | undefined;
    telefon: string | undefined;
    turu: string | undefined;
    "tedarikciPuanı": number | undefined;
    tedarikciSinifi: string | undefined;
    calismaBaslamaTarihi: DateOnly;
    degerlendirmeTarihi: DateOnly;
    sektor: string | undefined;
    referans: string | undefined;
    sirketTuru: CustomerType;
    ulkeAdi: string | undefined;
    vergiNumarasi: string | undefined;
    contacts: CustomerContactDto[] | undefined;
}

export interface CustomerDtoForUpdate {
    firma: string | undefined;
    yetkili: string | undefined;
    adres: string | undefined;
    email: string | undefined;
    telefon: string | undefined;
    turu: string | undefined;
    "tedarikciPuanı": number | undefined;
    tedarikciSinifi: string | undefined;
    calismaBaslamaTarihi: DateOnly;
    degerlendirmeTarihi: DateOnly;
    sektor: string | undefined;
    referans: string | undefined;
    sirketTuru: CustomerType;
    ulkeAdi: string | undefined;
    vergiNumarasi: string | undefined;
    id: number;
    contacts: CustomerContactDto[] | undefined;
}

export interface CustomerDtoIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: CustomerDto[] | undefined;
    isSuccess: boolean;
}

export enum CustomerType {
    Musteri = 0,
    Tedarikci = 1,
    Diger = 2,
}

export interface DateOnly {
    year: number;
    month: number;
    day: number;
    dayOfWeek: DayOfWeek;
    readonly dayOfYear: number;
    readonly dayNumber: number;
}

export enum DayOfWeek {
    Sunday = 0,
    Monday = 1,
    Tuesday = 2,
    Wednesday = 3,
    Thursday = 4,
    Friday = 5,
    Saturday = 6,
}

export interface DocumentDto {
}

export interface Education {
    id: number;
    egitimAdi: string | undefined;
    egitimNotu: string | undefined;
    egitimBaslangicTarihi: string | undefined;
    egitimBitisTarihi: string | undefined;
    gelecekEgitimTarihi: string | undefined;
    icKaynakMi: boolean;
    egiticiPersonelId: number | undefined;
    personelId: number | undefined;
    isActive: boolean | undefined;
    egitimSuresiDk: number | undefined;
    disKaynakAdi: string | undefined;
    updatedByUserId: number | undefined;
    createdByUserId: number | undefined;
    createdAt: Date | undefined;
    updatedAt: Date | undefined;
    egitimDegerlendirmeFormId: number | undefined;
    personelDegerlendirmeFormId: number | undefined;
    createdByUser: Users;
    educationFileMapping: EducationFileMapping[] | undefined;
    egiticiPersonel: Personel;
    egitimDegerlendirmeForm: Survey;
    personelDegerlendirmeForm: Survey;
    personelEducationMapping: PersonelEducationMapping[] | undefined;
    updatedByUser: Users;
}

export interface EducationFileMapping {
    id: number;
    educationId: number | undefined;
    fileId: number | undefined;
    uploadedAt: Date | undefined;
    uploadedBy: number | undefined;
    education: Education;
    file: FileRecord;
}

export interface EducationFileMappingInsertion {
    id: number | undefined;
    fileName: string | undefined;
    educationId: number | undefined;
    fileNameOrijinal: string | undefined;
    contentType: string | undefined;
    base64Data: string | undefined;
}

export interface EnterpriseDto {
    enterpriseName: string | undefined;
    shortName: string | undefined;
    logoUrl: string | undefined;
    sector: string | undefined;
    address: string | undefined;
    city: string | undefined;
    country: string | undefined;
    phone: string | undefined;
    email: string | undefined;
    website: string | undefined;
    contactPerson: string | undefined;
    contactTitle: string | undefined;
    contactPhone: string | undefined;
    contactEmail: string | undefined;
    taxOffice: string | undefined;
    taxNumber: string | undefined;
    registrationNumber: string | undefined;
    iban: string | undefined;
    currency: string | undefined;
    machinePark: string | undefined;
    productionCapacity: string | undefined;
    materialsWorkedOn: string | undefined;
    qualityCertificates: string | undefined;
    exportStatus: boolean | undefined;
    employeeCount: number | undefined;
    id: number;
    createdAt: Date | undefined;
    updatedAt: Date | undefined;
}

export interface EnterpriseDtoForInsertion {
    enterpriseName: string | undefined;
    shortName: string | undefined;
    logoUrl: string | undefined;
    sector: string | undefined;
    address: string | undefined;
    city: string | undefined;
    country: string | undefined;
    phone: string | undefined;
    email: string | undefined;
    website: string | undefined;
    contactPerson: string | undefined;
    contactTitle: string | undefined;
    contactPhone: string | undefined;
    contactEmail: string | undefined;
    taxOffice: string | undefined;
    taxNumber: string | undefined;
    registrationNumber: string | undefined;
    iban: string | undefined;
    currency: string | undefined;
    machinePark: string | undefined;
    productionCapacity: string | undefined;
    materialsWorkedOn: string | undefined;
    qualityCertificates: string | undefined;
    exportStatus: boolean | undefined;
    employeeCount: number | undefined;
}

export interface EnterpriseDtoForUpdate {
    enterpriseName: string | undefined;
    shortName: string | undefined;
    logoUrl: string | undefined;
    sector: string | undefined;
    address: string | undefined;
    city: string | undefined;
    country: string | undefined;
    phone: string | undefined;
    email: string | undefined;
    website: string | undefined;
    contactPerson: string | undefined;
    contactTitle: string | undefined;
    contactPhone: string | undefined;
    contactEmail: string | undefined;
    taxOffice: string | undefined;
    taxNumber: string | undefined;
    registrationNumber: string | undefined;
    iban: string | undefined;
    currency: string | undefined;
    machinePark: string | undefined;
    productionCapacity: string | undefined;
    materialsWorkedOn: string | undefined;
    qualityCertificates: string | undefined;
    exportStatus: boolean | undefined;
    employeeCount: number | undefined;
}

export interface EnterpriseDtoIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: EnterpriseDto[] | undefined;
    isSuccess: boolean;
}

export interface FileRecord {
    id: number;
    fileName: string | undefined;
    storedFileName: string | undefined;
    filePath: string | undefined;
    contentType: string | undefined;
    sizeKb: number | undefined;
    uploadedAt: Date | undefined;
    uploadedBy: number | undefined;
    relatedEntityName: string | undefined;
    relatedEntityId: number | undefined;
    type: number | undefined;
    educationFileMapping: EducationFileMapping[] | undefined;
    uploadedByNavigation: Users;
}

export interface FileRecordDto {
    fileName: string | undefined;
    contentType: string | undefined;
    sizeKb: number | undefined;
    id: number;
    filePath: string | undefined;
}

export interface FileRecordDtoForInsertion {
    fileName: string | undefined;
    contentType: string | undefined;
    sizeKb: number | undefined;
    content: string | undefined;
    uploadedBy: number | undefined;
    relatedEntityName: string | undefined;
    relatedEntityId: number | undefined;
    type: number | undefined;
}

export interface FileRecordDtoIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: FileRecordDto[] | undefined;
    isSuccess: boolean;
}

export interface GroupDto {
    title: string;
    color: string | undefined;
    id: number;
    boardId: number;
}

export interface ItemDto {
    name: string;
    id: number;
    groupId: number;
    parentItemId: number | undefined;
    itemValues: ItemValueDto[] | undefined;
}

export interface ItemTreeDto {
    name: string;
    id: number;
    groupId: number;
    order: number;
    parentItemId: number | undefined;
    itemValues: ItemValueDto[] | undefined;
    inverseParentItem: ItemTreeDto[] | undefined;
}

export interface ItemValueDto {
    id: number;
    value: string | undefined;
    itemId: number;
    columnId: number;
}

export interface KysDocument {
    id: number;
    documentNo: string | undefined;
    documentName: string | undefined;
    content: string | undefined;
    contentType: string | undefined;
    publishedDate: Date;
    revisionNumber: string | undefined;
    revisionDescription: string | undefined;
    revisionDate: Date | undefined;
    updatedByUserId: number | undefined;
    createdByUserId: number | undefined;
    createdAt: Date | undefined;
    updatedAt: Date | undefined;
    kysDocumentType: string | undefined;
    isArchive: boolean | undefined;
    isUserUploaded: boolean | undefined;
    createdByUser: Users;
    updatedByUser: Users;
}

export interface Log {
    id: number;
    serviceName: string | undefined;
    statusCode: number | undefined;
    message: string | undefined;
    process: string | undefined;
    result: string | undefined;
    ip: string | undefined;
    userId: number | undefined;
    createdAt: Date | undefined;
    user: Users;
}

export interface MailSendDto {
    toEmail: string | undefined;
    subject: string | undefined;
    body: string | undefined;
    smtpPort: number;
    smtpHost: string | undefined;
    smtpUser: string | undefined;
    smtpPassword: string | undefined;
    attachmentPaths: string[] | undefined;
}

export interface MoveItemDto {
    itemId: number;
    destinationGroupId: number;
    destinationIndex: number;
    parentItemId: number | undefined;
}

export interface Operation {
    operationType: OperationType;
    path: string | undefined;
    op: string | undefined;
    from: string | undefined;
    value: any | undefined;
}

export enum OperationType {
    Add = 0,
    Remove = 1,
    Replace = 2,
    Move = 3,
    Copy = 4,
    Test = 5,
    Invalid = 6,
}

export interface Opportunity {
    id: number;
    title: string | undefined;
    description: string | undefined;
    value: number | undefined;
    opportunityStage: number;
    customerId: number | undefined;
    probability: number | undefined;
    expectedCloseDate: Date | undefined;
    createdAt: Date | undefined;
    createdByUserId: number | undefined;
    customerContactPersonId: number | undefined;
    startDate: Date | undefined;
    currency: string | undefined;
    createdByUser: Users;
    customer: Company;
    customerContactPerson: CompanyPerson;
    priceOffer: PriceOffer[] | undefined;
}

export interface OpportunityDto {
    title: string | undefined;
    description: string | undefined;
    value: number | undefined;
    customerContactPersonId: number | undefined;
    activity: ActivityDto[] | undefined;
    expectedCloseDate: Date | undefined;
    startDate: Date | undefined;
    files: FileRecordDto[] | undefined;
    notes: string[] | undefined;
    createdByUserId: number | undefined;
    customerId: number | undefined;
    currency: string | undefined;
    opportunityStage: OpportunityStage;
    probability: number | undefined;
    id: number;
    customerName: string | undefined;
}

export interface OpportunityDtoForInsertion {
    title: string | undefined;
    description: string | undefined;
    value: number | undefined;
    customerContactPersonId: number | undefined;
    activity: ActivityDto[] | undefined;
    expectedCloseDate: Date | undefined;
    startDate: Date | undefined;
    files: FileRecordDto[] | undefined;
    notes: string[] | undefined;
    createdByUserId: number | undefined;
    customerId: number | undefined;
    currency: string | undefined;
    opportunityStage: OpportunityStage;
    probability: number | undefined;
}

export interface OpportunityDtoForUpdate {
    title: string | undefined;
    description: string | undefined;
    value: number | undefined;
    customerContactPersonId: number | undefined;
    activity: ActivityDto[] | undefined;
    expectedCloseDate: Date | undefined;
    startDate: Date | undefined;
    files: FileRecordDto[] | undefined;
    notes: string[] | undefined;
    createdByUserId: number | undefined;
    customerId: number | undefined;
    currency: string | undefined;
    opportunityStage: OpportunityStage;
    probability: number | undefined;
    id: number;
}

export interface OpportunityDtoIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: OpportunityDto[] | undefined;
    isSuccess: boolean;
}

export enum OpportunityStage {
    New = 0,
    Qualification = 1,
    Proposal = 2,
    Negotiation = 3,
    Contract = 4,
    Won = 5,
    Lost = 6,
}

export interface OvertimeDtoForInsertion {
    id: number;
    projeKodu: string | undefined;
    projeAdi: string | undefined;
    parcaKodu: string | undefined;
    parcaAdi: string | undefined;
    revizyon: string | undefined;
    seriNo: string | undefined;
    aciklama: string | undefined;
    personel: string | undefined;
    departman: string | undefined;
    tarih: string | undefined;
    baslamaSaati: string | undefined;
    bitisSaati: string | undefined;
    suresi: string | undefined;
    tezgah_isIstasyon: string | undefined;
    gorevVeren: string | undefined;
    yonetimOnay: string | undefined;
    turu: string | undefined;
    durumu: string | undefined;
    durumAciklama: string | undefined;
    kullanici: string | undefined;
    tar: DateOnly;
    isActive: boolean | undefined;
}

export interface Personel {
    id: number;
    personelKodu: string | undefined;
    personelAdi: string | undefined;
    personelSoyadi: string | undefined;
    personelTCKN: string | undefined;
    personelDepartman: string | undefined;
    personelGorevi: string | undefined;
    cinsiyet: string | undefined;
    dogumYeri: string | undefined;
    dogumTarihi: string | undefined;
    kanGrubu: string | undefined;
    ePosta: string | undefined;
    telefonNo: string | undefined;
    mezuniyetBolumu: string | undefined;
    egitimDurumu: string | undefined;
    iseGirisTarihi: string | undefined;
    "istenAyrılısTarihi": string | undefined;
    anneAdi: string | undefined;
    babaAdi: string | undefined;
    sgkSicilNo: string | undefined;
    sozlesmeTuru: string | undefined;
    acilAramaTel: string | undefined;
    personelQRKodu: string | undefined;
    personelResmi: string | undefined;
    isActive: boolean | undefined;
    ekleyen: string | undefined;
    eklemeZaman: Date | undefined;
    degistiren: string | undefined;
    degistirmeZaman: Date | undefined;
    resim: string | undefined;
    durumu: string | undefined;
    pK3: string | undefined;
    netUcreti: number;
    mailImzasi: string | undefined;
    education: Education[] | undefined;
    personelEducationMapping: PersonelEducationMapping[] | undefined;
    surveyResponse: SurveyResponse[] | undefined;
}

export interface PersonelCombinedResponse {
    personelName: PersonelDtoForName;
    personel: PersonelDto;
}

export interface PersonelCombinedResponseApiResponse {
    message: string | undefined;
    statusCode: number;
    result: PersonelCombinedResponse;
    isSuccess: boolean;
}

export interface PersonelDto {
    id: number;
    personelAdi: string | undefined;
    personelKodu: string | undefined;
    personelSoyadi: string | undefined;
    personelDepartman: string | undefined;
    personelGorevi: string | undefined;
    telefonNo: string | undefined;
    ePosta: string | undefined;
    iseGirisTarihi: string | undefined;
    isActive: boolean;
    mailImzasi: string | undefined;
}

export interface PersonelDtoForInsertion {
    personelKodu: string | undefined;
    personelAdi: string | undefined;
    personelSoyadi: string | undefined;
    personelTCKN: string | undefined;
    personelDepartman: string | undefined;
    personelGorevi: string | undefined;
    cinsiyet: string | undefined;
    dogumYeri: string | undefined;
    dogumTarihi: string | undefined;
    kanGrubu: string | undefined;
    ePosta: string | undefined;
    telefonNo: string | undefined;
    mezuniyetBolumu: string | undefined;
    egitimDurumu: string | undefined;
    iseGirisTarihi: string | undefined;
    "istenAyrılısTarihi": string | undefined;
    anneAdi: string | undefined;
    babaAdi: string | undefined;
    sgkSicilNo: string | undefined;
    sozlesmeTuru: string | undefined;
    acilAramaTel: string | undefined;
    isActive: boolean | undefined;
    ekleyen: string | undefined;
    eklemeZaman: Date | undefined;
    degistiren: string | undefined;
    degistirmeZaman: Date | undefined;
    durumu: string | undefined;
    pK3: string | undefined;
    netUcreti: number;
    mailImzasi: string | undefined;
}

export interface PersonelDtoForName {
    id: number;
    personelAdi: string | undefined;
    personelSoyadi: string | undefined;
    personelGorevi: string | undefined;
    isActive: boolean;
}

export interface PersonelDtoForUpdate {
    personelAdi: string | undefined;
    personelSoyadi: string | undefined;
    personelTCKN: string | undefined;
    personelDepartman: string | undefined;
    personelGorevi: string | undefined;
    cinsiyet: string | undefined;
    dogumYeri: string | undefined;
    dogumTarihi: string | undefined;
    kanGrubu: string | undefined;
    ePosta: string | undefined;
    telefonNo: string | undefined;
    mezuniyetBolumu: string | undefined;
    egitimDurumu: string | undefined;
    iseGirisTarihi: string | undefined;
    "istenAyrılısTarihi": string | undefined;
    anneAdi: string | undefined;
    babaAdi: string | undefined;
    sgkSicilNo: string | undefined;
    sozlesmeTuru: string | undefined;
    acilAramaTel: string | undefined;
    mailImzasi: string | undefined;
}

export interface PersonelEducationAssignDto {
    state: number;
    isActive: boolean | undefined;
    createdAt: Date | undefined;
    updatedAt: Date | undefined;
}

export interface PersonelEducationMapping {
    id: number;
    personelId: number;
    educationId: number;
    state: number;
    isActive: boolean | undefined;
    createdAt: Date | undefined;
    updatedAt: Date | undefined;
    education: Education;
    personel: Personel;
}

export interface PersonelEducationMappingDto {
    id: number;
    personelId: number;
    personelEducationPlanId: number;
    state: number;
}

export interface PersonelEducationPlanDto {
    id: number;
    egitimAdi: string | undefined;
    egitimNotu: string | undefined;
    egitimBaslangicTarihi: string | undefined;
    egitimBitisTarihi: string | undefined;
    gelecekEgitimTarihi: string | undefined;
    icKaynakMi: boolean;
    egiticiPersonelId: number | undefined;
    egiticiPersonelAdi: string | undefined;
    isActive: boolean | undefined;
    egitimSuresiDk: number | undefined;
    disKaynakAdi: string | undefined;
    egitimDegerlendirmeFormId: number | undefined;
    personelDegerlendirmeFormId: number | undefined;
    dosyalar: FileRecord[] | undefined;
    atama: PersonelEducationAssignDto;
}

export interface PersonelEducationResultDto {
    id: number;
    egitimAdi: string | undefined;
    state: number;
    puan: number;
}

export enum PersonelEgitimDurumlari {
    AtamaYapildi = 0,
    KayitlarOkundu = 1,
    SinavYapildi = 2,
    SinavBasarili = 3,
    SinavBasarisiz = 4,
    AtamaYapilmamis = 5,
    AtamasiKaldirilmis = 6,
}

export interface PersonelWithEducationDto {
    id: number;
    personelAdi: string | undefined;
    personelKodu: string | undefined;
    personelSoyadi: string | undefined;
    personelDepartman: string | undefined;
    personelGorevi: string | undefined;
    educations: PersonelEducationResultDto[] | undefined;
}

export interface PersonelWithEducationDtoApiResponse {
    message: string | undefined;
    statusCode: number;
    result: PersonelWithEducationDto;
    isSuccess: boolean;
}

export interface PriceOffer {
    id: number;
    teklifBelgeNo: string | undefined;
    firmaAdi: string | undefined;
    teklifTarihi: Date | undefined;
    teklifGecerlilikTarihi: Date | undefined;
    teklifAciklama: string | undefined;
    teklifOnay: string | undefined;
    durumu: string | undefined;
    projeNo: string | undefined;
    talepNo: string | undefined;
    firma_Id: number | undefined;
    talep_Id: number | undefined;
    isActive: boolean | undefined;
    ekleyen: string | undefined;
    eklemeZaman: Date | undefined;
    degistiren: string | undefined;
    degistirmeZaman: Date | undefined;
    siparisMi: boolean | undefined;
    servisMi: boolean | undefined;
    opportunityId: number | undefined;
    referansNo: string | undefined;
    teslimTarihi: DateOnly;
    belgeIndirimOraniYuzde: number | undefined;
    garantiSuresiGun: number | undefined;
    toplamTutar: number | undefined;
    contracts: Contracts[] | undefined;
    opportunity: Opportunity;
    priceOfferLine: PriceOfferLine[] | undefined;
    purchaseOrders: PurchaseOrders[] | undefined;
}

export interface PriceOfferDto {
    teklifBelgeNo: string | undefined;
    teklifTarihi: Date | undefined;
    teklifGecerlilikTarihi: Date | undefined;
    teklifAciklama: string | undefined;
    teklifOnay: string | undefined;
    durumu: PriceOfferState;
    talepNo: string | undefined;
    ekleyen: string | undefined;
    degistiren: string | undefined;
    firma_Id: number | undefined;
    talep_Id: number | undefined;
    opportunityId: number | undefined;
    referansNo: string | undefined;
    teslimTarihi: DateOnly;
    belgeIndirimOraniYuzde: number | undefined;
    garantiSuresiGun: number | undefined;
    toplamTutar: number | undefined;
    id: number;
    priceOfferLine: PriceOfferLineDto[] | undefined;
}

export interface PriceOfferDtoForInsertion {
    teklifBelgeNo: string | undefined;
    teklifTarihi: Date | undefined;
    teklifGecerlilikTarihi: Date | undefined;
    teklifAciklama: string | undefined;
    teklifOnay: string | undefined;
    durumu: PriceOfferState;
    talepNo: string | undefined;
    degistiren: string | undefined;
    firma_Id: number | undefined;
    talep_Id: number | undefined;
    opportunityId: number | undefined;
    referansNo: string | undefined;
    teslimTarihi: DateOnly;
    belgeIndirimOraniYuzde: number | undefined;
    garantiSuresiGun: number | undefined;
    toplamTutar: number | undefined;
    ekleyen: string | undefined;
    priceOfferLine: PriceOfferLineDtoForInsertion[] | undefined;
}

export interface PriceOfferDtoForUpdate {
    teklifBelgeNo: string | undefined;
    teklifTarihi: Date | undefined;
    teklifGecerlilikTarihi: Date | undefined;
    teklifAciklama: string | undefined;
    teklifOnay: string | undefined;
    durumu: PriceOfferState;
    talepNo: string | undefined;
    degistiren: string | undefined;
    firma_Id: number | undefined;
    talep_Id: number | undefined;
    opportunityId: number | undefined;
    referansNo: string | undefined;
    teslimTarihi: DateOnly;
    belgeIndirimOraniYuzde: number | undefined;
    garantiSuresiGun: number | undefined;
    toplamTutar: number | undefined;
    ekleyen: string | undefined;
    priceOfferLine: PriceOfferLineDtoForUpdate[] | undefined;
}

export interface PriceOfferDtoIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: PriceOfferDto[] | undefined;
    isSuccess: boolean;
}

export interface PriceOfferLine {
    id: number;
    malzemeKodu: string | undefined;
    malzemeAdi: string | undefined;
    miktar: number | undefined;
    birimi: string | undefined;
    birimFiyat: number | undefined;
    toplamFiyat: number | undefined;
    teslimTarih: DateOnly;
    teslimSuresi: string | undefined;
    priceOffer_Id: number | undefined;
    isActive: boolean | undefined;
    ekleyen: string | undefined;
    eklemeZaman: Date | undefined;
    degistiren: string | undefined;
    degistirmeZaman: Date | undefined;
    paraBirimi: string | undefined;
    indirimOraniYuzde: number | undefined;
    kdvOraniYuzde: number | undefined;
    opsiyonMu: boolean | undefined;
    priceOffer: PriceOffer;
}

export interface PriceOfferLineDto {
    malzemeKodu: string | undefined;
    malzemeAdi: string | undefined;
    miktar: number | undefined;
    birimi: string | undefined;
    birimFiyat: number | undefined;
    toplamFiyat: number | undefined;
    teslimTarih: DateOnly;
    teslimSuresi: string | undefined;
    paraBirimi: string | undefined;
    indirimOraniYuzde: number | undefined;
    kdvOraniYuzde: number | undefined;
    opsiyonMu: boolean | undefined;
}

export interface PriceOfferLineDtoForInsertion {
    malzemeKodu: string | undefined;
    malzemeAdi: string | undefined;
    miktar: number | undefined;
    birimi: string | undefined;
    birimFiyat: number | undefined;
    toplamFiyat: number | undefined;
    teslimTarih: DateOnly;
    teslimSuresi: string | undefined;
    paraBirimi: string | undefined;
    indirimOraniYuzde: number | undefined;
    kdvOraniYuzde: number | undefined;
    opsiyonMu: boolean | undefined;
}

export interface PriceOfferLineDtoForUpdate {
    malzemeKodu: string | undefined;
    malzemeAdi: string | undefined;
    miktar: number | undefined;
    birimi: string | undefined;
    birimFiyat: number | undefined;
    toplamFiyat: number | undefined;
    teslimTarih: DateOnly;
    teslimSuresi: string | undefined;
    paraBirimi: string | undefined;
    indirimOraniYuzde: number | undefined;
    kdvOraniYuzde: number | undefined;
    opsiyonMu: boolean | undefined;
}

export enum PriceOfferState {
    Draft = 1,
    Accepted = 2,
    Rejected = 3,
    Sended = 4,
    Withdrawn = 5,
    Waiting = 6,
}

export interface ProblemDetails {
    type: string | undefined;
    title: string | undefined;
    status: number | undefined;
    detail: string | undefined;
    instance: string | undefined;

    [key: string]: any;
}

export interface Products {
    id: number;
    productCode: string | undefined;
    productName: string | undefined;
    notes: string | undefined;
    parcaTipi: string | undefined;
    olcuBirimi: string | undefined;
    malzemeTuru: string | undefined;
    muadilMalzeme: string | undefined;
    tedarikTipi: string | undefined;
    firmaAdi: string | undefined;
    barkod: string | undefined;
    pictures: string | undefined;
    projeNo: string | undefined;
    isActive: boolean | undefined;
    eklemeZaman: Date | undefined;
    degistirmeZaman: Date | undefined;
    depo: string | undefined;
    seriLotNo: string | undefined;
    saklamaKosulu: string | undefined;
    sonKullanmaTarihi: string | undefined;
    revizyonNo: string | undefined;
    revizyonTarih: string | undefined;
    varyantSecenegi: boolean | undefined;
    urunKonfiguratoru: boolean | undefined;
    nsnKodu: string | undefined;
    seriNumarasi: string | undefined;
    stokYeri: string | undefined;
    stokMiktar: string | undefined;
    birimFiyat: number | undefined;
    paraBirimi: string | undefined;
    purchaseOrdersLine: PurchaseOrdersLine[] | undefined;
}

export interface ProductsDtoForInsertion {
    id: number | undefined;
    productCode: string | undefined;
    productName: string | undefined;
    notes: string | undefined;
    parcaTipi: string | undefined;
    olcuBirimi: string | undefined;
    malzemeTuru: string | undefined;
    muadilMalzeme: string | undefined;
    tedarikTipi: string | undefined;
    firmaAdi: string | undefined;
    barkod: string | undefined;
    pictures: string | undefined;
    projeNo: string | undefined;
    isActive: boolean | undefined;
    eklemeZaman: Date | undefined;
    degistirmeZaman: Date | undefined;
    depo: string | undefined;
    seriLotNo: string | undefined;
    saklamaKosulu: string | undefined;
    sonKullanmaTarihi: string | undefined;
    revizyonNo: string | undefined;
    revizyonTarih: string | undefined;
    varyantSecenegi: boolean | undefined;
    urunKonfiguratoru: boolean | undefined;
    nsnKodu: string | undefined;
    seriNumarasi: string | undefined;
    stokYeri: string | undefined;
    stokMiktar: string | undefined;
    birimFiyat: number | undefined;
    paraBirimi: string | undefined;
}

export interface ProductsIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: Products[] | undefined;
    isSuccess: boolean;
}

export interface ProjectFiles {
    id: number;
    dosyaAdi: string | undefined;
    uzantisi: string | undefined;
    bytes: string | undefined;
    projectReport_Id: number | undefined;
    isActive: boolean | undefined;
}

export interface ProjectReportDtoForInsertion {
    id: number;
    raporNo: string | undefined;
    tarih: string | undefined;
    projeNo: string | undefined;
    projeAdi: string | undefined;
    parcaKodu: string | undefined;
    parcaAdi: string | undefined;
    revizyon: string | undefined;
    hazirlayan: string | undefined;
    onaylayan: string | undefined;
    aciklama: string | undefined;
    durumu: string | undefined;
    durumAciklama: string | undefined;
    kullanici: string | undefined;
    isActive: boolean | undefined;
    dosyalar: ProjectFiles[] | undefined;
}

export interface ProjectsDtoForInsertion {
    id: number;
    projeNo: string | undefined;
    projeAdi: string | undefined;
    dgtNo: string | undefined;
    nsnKodu: string | undefined;
    turu: string | undefined;
    miktar: number | undefined;
    yedekMiktar: number | undefined;
    baslangicZamani: string | undefined;
    bitisZamani: string | undefined;
    toplamSure: string | undefined;
    aciklama: string | undefined;
    sorumluPersonel: string | undefined;
    durum: string | undefined;
    isActive: boolean | undefined;
}

export interface PurchaseOrderDto {
    id: number;
    projeNo: string | undefined;
    firma_Id: number | undefined;
    siparisNo: string | undefined;
    faturaNo: string | undefined;
    firmaAdi: string | undefined;
    yetkiliKisi: string | undefined;
    siparisTarihi: DateOnly;
    teslimTarihi: DateOnly;
    aciklama: string | undefined;
    durumu: string | undefined;
    onayAcikla: string | undefined;
    siparisKosullari: string | undefined;
    kaliteKosullari: string | undefined;
    siparisTipi: string | undefined;
    turu: string | undefined;
    toplamTutar: number | undefined;
    toplamIndirimOraniYuzde: number | undefined;
    priceOfferId: number | undefined;
    purchaseOrderLine: PurchaseOrderLineDto[] | undefined;
}

export interface PurchaseOrderDtoForInsertion {
    firma_Id: number | undefined;
    firmaAdi: string | undefined;
    yetkiliKisi: string | undefined;
    siparisTarihi: DateOnly;
    teslimTarihi: DateOnly;
    aciklama: string | undefined;
    durumu: string | undefined;
    onayAcikla: string | undefined;
    siparisKosullari: string | undefined;
    kaliteKosullari: string | undefined;
    siparisTipi: string | undefined;
    turu: string | undefined;
    toplamIndirimOraniYuzde: number | undefined;
    priceOfferId: number | undefined;
    toplamTutar: number | undefined;
    purchaseOrderLine: PurchaseOrderLineDtoForInsertion[] | undefined;
}

export interface PurchaseOrderDtoForUpdate {
    firma_Id: number | undefined;
    firmaAdi: string | undefined;
    yetkiliKisi: string | undefined;
    siparisTarihi: DateOnly;
    teslimTarihi: DateOnly;
    aciklama: string | undefined;
    durumu: string | undefined;
    onayAcikla: string | undefined;
    siparisKosullari: string | undefined;
    kaliteKosullari: string | undefined;
    siparisTipi: string | undefined;
    turu: string | undefined;
    toplamIndirimOraniYuzde: number | undefined;
    priceOfferId: number | undefined;
    toplamTutar: number | undefined;
    purchaseOrderLine: PurchaseOrderLineDtoForUpdate[] | undefined;
    id: number;
}

export interface PurchaseOrderDtoIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: PurchaseOrderDto[] | undefined;
    isSuccess: boolean;
}

export interface PurchaseOrderLineDto {
    id: number;
    projeKodu: string | undefined;
    toplamFiyat: number | undefined;
    faturaNo: string | undefined;
    order_Id: number | undefined;
    product_Id: number | undefined;
    isActive: boolean | undefined;
    malzemeKodu: string | undefined;
    malzemeAdi: string | undefined;
    miktar: number | undefined;
    birimi: string | undefined;
    birimFiyat: number | undefined;
    paraBirimi: string | undefined;
    teslimTarih: DateOnly;
    aciklama: string | undefined;
    tamamTarihi: DateOnly;
    durumu: string | undefined;
    stogaAktarildimi: boolean | undefined;
    indirimOraniYuzde: number | undefined;
    kdvOraniYuzde: number | undefined;
}

export interface PurchaseOrderLineDtoForInsertion {
    malzemeKodu: string | undefined;
    malzemeAdi: string | undefined;
    miktar: number | undefined;
    birimi: string | undefined;
    birimFiyat: number | undefined;
    paraBirimi: string | undefined;
    teslimTarih: DateOnly;
    aciklama: string | undefined;
    tamamTarihi: DateOnly;
    durumu: string | undefined;
    stogaAktarildimi: boolean | undefined;
    order_Id: number | undefined;
    product_Id: number | undefined;
    indirimOraniYuzde: number | undefined;
    kdvOraniYuzde: number | undefined;
}

export interface PurchaseOrderLineDtoForUpdate {
    malzemeKodu: string | undefined;
    malzemeAdi: string | undefined;
    miktar: number | undefined;
    birimi: string | undefined;
    birimFiyat: number | undefined;
    paraBirimi: string | undefined;
    teslimTarih: DateOnly;
    aciklama: string | undefined;
    tamamTarihi: DateOnly;
    durumu: string | undefined;
    stogaAktarildimi: boolean | undefined;
    order_Id: number | undefined;
    product_Id: number | undefined;
    indirimOraniYuzde: number | undefined;
    kdvOraniYuzde: number | undefined;
    id: number;
}

export interface PurchaseOrders {
    id: number;
    projeNo: string | undefined;
    siparisNo: string | undefined;
    talepNo: string | undefined;
    firmaAdi: string | undefined;
    yetkiliKisi: string | undefined;
    siparisTarihi: DateOnly;
    teslimTarihi: DateOnly;
    aciklama: string | undefined;
    firma_Id: number | undefined;
    durumu: string | undefined;
    isActive: boolean | undefined;
    onayAcikla: string | undefined;
    faturaNo: string | undefined;
    siparisKosullari: string | undefined;
    kaliteKosullari: string | undefined;
    siparisTipi: string | undefined;
    turu: string | undefined;
    toplamIndirimOraniYuzde: number | undefined;
    priceOfferId: number | undefined;
    toplamTutar: number | undefined;
    contracts: Contracts[] | undefined;
    firma: Company;
    priceOffer: PriceOffer;
    purchaseOrdersLine: PurchaseOrdersLine[] | undefined;
}

export interface PurchaseOrdersLine {
    id: number;
    projeKodu: string | undefined;
    malzemeKodu: string | undefined;
    malzemeAdi: string | undefined;
    miktar: number | undefined;
    birimi: string | undefined;
    birimFiyat: number | undefined;
    toplamFiyat: number | undefined;
    paraBirimi: string | undefined;
    teslimTarih: DateOnly;
    aciklama: string | undefined;
    tamamTarihi: DateOnly;
    durumu: string | undefined;
    faturaNo: string | undefined;
    order_Id: number | undefined;
    stogaAktarildimi: boolean | undefined;
    isActive: boolean | undefined;
    indirimOraniYuzde: number | undefined;
    kdvOraniYuzde: number | undefined;
    product_Id: number | undefined;
    order: PurchaseOrders;
    product: Products;
}

export enum QuestionType {
    Text = 0,
    MultipleChoice = 1,
}

export interface ReorderColumnsDto {
    orderedColumnIds: number[];
}

export interface ReorderGroupsDto {
    groupId: number;
    newIndex: number;
    orderedGroupIds: number[];
}

export interface ReviewList1Dto {
    soru: string | undefined;
    evet: boolean | undefined;
    hayir: boolean | undefined;
    bolum: string | undefined;
    aciklama: string | undefined;
    id: number;
}

export interface ReviewList2Dto {
    soru: string | undefined;
    evet: boolean | undefined;
    hayir: boolean | undefined;
    imza: string | undefined;
    id: number;
}

export interface ReviewMetadataDto {
    musteriAdi: string | undefined;
    projeAdi: string | undefined;
    siparisNo: string | undefined;
    tarih: DateOnly;
    id: number;
    reviewList1: ReviewList1Dto[] | undefined;
    reviewList2: ReviewList2Dto[] | undefined;
}

export interface ReviewMetadataDtoForInsertion {
    musteriAdi: string | undefined;
    projeAdi: string | undefined;
    siparisNo: string | undefined;
    tarih: DateOnly;
    reviewList1: ReviewList1Dto[] | undefined;
    reviewList2: ReviewList2Dto[] | undefined;
}

export interface ReviewMetadataDtoForUpdate {
    musteriAdi: string | undefined;
    projeAdi: string | undefined;
    siparisNo: string | undefined;
    tarih: DateOnly;
    reviewList1: ReviewList1Dto[] | undefined;
    reviewList2: ReviewList2Dto[] | undefined;
}

export interface ReviewMetadataDtoIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: ReviewMetadataDto[] | undefined;
    isSuccess: boolean;
}

export interface Services {
    id: number;
    name: string | undefined;
    endPoint: string | undefined;
    userId: number | undefined;
    createdAt: Date | undefined;
    updatedAt: Date | undefined;
    user: Users;
}

export interface ServicesDtoForInsertion {
    name: string | undefined;
    endPoint: string | undefined;
    userId: string | undefined;
    createdAt: Date | undefined;
}

export interface ServicesDtoForUpdate {
    name: string | undefined;
    endPoint: string | undefined;
    userId: string | undefined;
    id: number;
    trackChanges: boolean | undefined;
    updatedAt: Date | undefined;
}

export interface StaffLeaveDtoForInsertion {
    id: number | undefined;
    personel: string | undefined;
    birimi: string | undefined;
    izinNedeni: string | undefined;
    talepTarihi: string | undefined;
    izinTuru: string | undefined;
    adres: string | undefined;
    baslangicTarih: string | undefined;
    baslaSaat: string | undefined;
    bitisTarih: string | undefined;
    bitisSaat: string | undefined;
    yerineBakacakKisi: string | undefined;
    gorevBaslaTarihi: string | undefined;
    gorevBaslaSaati: string | undefined;
    bolumSorumlusu: string | undefined;
    iK_Onay: string | undefined;
    yonetim_Onay: string | undefined;
    durumu: string | undefined;
    durumAciklama: string | undefined;
    kullanici: string | undefined;
    personelId: number | undefined;
    isActive: boolean | undefined;
}

export interface SubmitSurveyDto {
    surveyId: number;
    personelId: number | undefined;
    personelEducationPlanId: number | undefined;
    answers: AnswerDto[] | undefined;
}

export interface Survey {
    id: number;
    title: string | undefined;
    description: string | undefined;
    surveyType: number;
    updatedByUserId: number | undefined;
    createdByUserId: number | undefined;
    createdAt: Date | undefined;
    updatedAt: Date | undefined;
    puanIsShow: boolean | undefined;
    createdByUser: Users;
    educationEgitimDegerlendirmeForm: Education[] | undefined;
    educationPersonelDegerlendirmeForm: Education[] | undefined;
    surveyQuestionGroup: SurveyQuestionGroup[] | undefined;
    surveyResponse: SurveyResponse[] | undefined;
    updatedByUser: Users;
}

export interface SurveyAnswer {
    id: number;
    surveyResponseId: number;
    questionId: number;
    optionId: number | undefined;
    textAnswer: string | undefined;
    optionDescription: string | undefined;
    option: SurveyOption;
    question: SurveyQuestion;
    surveyResponse: SurveyResponse;
}

export interface SurveyOption {
    id: number;
    text: string | undefined;
    puan: number | undefined;
    questionGroupId: number;
    questionGroup: SurveyQuestionGroup;
    surveyAnswer: SurveyAnswer[] | undefined;
}

export interface SurveyQuestion {
    id: number;
    text: string | undefined;
    type: number;
    questionGroupId: number;
    questionGroup: SurveyQuestionGroup;
    surveyAnswer: SurveyAnswer[] | undefined;
}

export interface SurveyQuestionGroup {
    id: number;
    name: string | undefined;
    parentGroupId: number | undefined;
    surveyId: number;
    inverseParentGroup: SurveyQuestionGroup[] | undefined;
    parentGroup: SurveyQuestionGroup;
    survey: Survey;
    surveyOption: SurveyOption[] | undefined;
    surveyQuestion: SurveyQuestion[] | undefined;
}

export interface SurveyResponse {
    id: number;
    surveyId: number;
    createdByPersonelId: number | undefined;
    personelEducationPlanId: number | undefined;
    createdByUserId: number | undefined;
    createdAt: Date | undefined;
    createdByPersonel: Personel;
    createdByUser: Users;
    survey: Survey;
    surveyAnswer: SurveyAnswer[] | undefined;
}

export enum SurveyType {
    Egitim = 0,
    Tedarikci = 1,
    Yetkinlik = 2,
    Diger = 3,
    Personel = 4,
}

export interface SystemLog {
    id: number;
    note: string | undefined;
    relatedEntityName: string | undefined;
    relatedEntityId: number;
    createdAt: Date | undefined;
    createdByUserId: number | undefined;
    type: number;
    createdByUser: Users;
}

export interface SystemLogDto {
    id: number;
    note: string | undefined;
    relatedEntityName: string | undefined;
    relatedEntityId: number;
    createdAt: Date | undefined;
    createdByUserId: number | undefined;
    type: number;
}

export interface SystemLogDtoForInsertion {
    note: string | undefined;
    relatedEntityName: string | undefined;
    relatedEntityId: number;
    type: number;
    createdByUserId: number | undefined;
}

export interface SystemLogDtoForUpdate {
    note: string | undefined;
    relatedEntityName: string | undefined;
    relatedEntityId: number;
    type: number;
    id: number;
}

export interface SystemLogDtoIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: SystemLogDto[] | undefined;
    isSuccess: boolean;
}

export interface TokenDto {
    user: Users;
    role: number;
    accessToken: string | undefined;
    refreshToken: string | undefined;
}

export interface UpdateBoardDto {
    name: string;
    description: string | undefined;
}

export interface UpdateBoardViewDto {
    name: string;
    order: number | undefined;
    settingsJson: string | undefined;
}

export interface UpdateColumnDto {
    title: string;
    settings: string | undefined;
}

export interface UpdateGroupDto {
    title: string;
    color: string | undefined;
}

export interface UpdateItemDto {
    name: string;
    parentItemId: number | undefined;
}

export interface UpdateItemValueDto {
    columnId: number;
    value: string | undefined;
}

export interface UserDtoForChangePassword {
    currentPassword: string;
    newPassword: string;
}

export interface UserDtoForCrm {
    id: number;
    name: string | undefined;
    surname: string | undefined;
    email: string | undefined;
    department: string | undefined;
    title: string | undefined;
    rolId: number | undefined;
    userName: string | undefined;
}

export interface UserDtoForCrmIEnumerableApiResponse {
    message: string | undefined;
    statusCode: number;
    result: UserDtoForCrm[] | undefined;
    isSuccess: boolean;
}

export interface UserForAuthenticationDto {
    userName: string | undefined;
    password: string | undefined;
}


export interface UserDtoForManipulation  {
    file?: string | null; 
    rolName: string | undefined;
    rolId: number | undefined;
    firstName?: string | null;
    lastName?: string | null;
    userName?: string | null;
    email?: string | null;
    tckno?: string | null;
    phoneNumber?: string | null;
    phoneNumber2?: string | null;
    address?: string | null;
    department?: string | null;
    departmentID?: number | null;
    title?: string | null;
    birthday?: string | Date | null;
    startDate?: string | Date | null;
    departureDate?: string | Date | null;
    gender?: string | null;
    isActive?: boolean | null;
  };
  
  export interface UserDtoForInsertion extends UserDtoForManipulation {
    password: string | null;
  };
  
  export interface UserDtoForUpdate extends UserDtoForManipulation {
    password?: string | null;
  };
export interface Users {
    id: number;
    tckno: string | undefined;
    name: string | undefined;
    surname: string | undefined;
    email: string | undefined;
    phone1: string | undefined;
    phone2: string | undefined;
    userName: string | undefined;
    password: string | undefined;
    department: string | undefined;
    departmentId: number | undefined;
    title: string | undefined;
    startDate: string | undefined;
    departureDate: string | undefined;
    rolName: string | undefined;
    rolId: number | undefined;
    cinsiyet: string | undefined;
    personel_Id: number | undefined;
    isActive: boolean | undefined;
    activityAssignedToUser: Activity[] | undefined;
    activityCreatedByUser: Activity[] | undefined;
    calendarEventAssigned: CalendarEvent[] | undefined;
    calendarEventCreatedByNavigation: CalendarEvent[] | undefined;
    cashAccountCreatedByNavigation: CashAccount[] | undefined;
    cashAccountUpdatedByNavigation: CashAccount[] | undefined;
    educationCreatedByUser: Education[] | undefined;
    educationUpdatedByUser: Education[] | undefined;
    fileRecord: FileRecord[] | undefined;
    kysDocumentCreatedByUser: KysDocument[] | undefined;
    kysDocumentUpdatedByUser: KysDocument[] | undefined;
    log: Log[] | undefined;
    opportunity: Opportunity[] | undefined;
    services: Services[] | undefined;
    surveyCreatedByUser: Survey[] | undefined;
    surveyResponse: SurveyResponse[] | undefined;
    surveyUpdatedByUser: Survey[] | undefined;
    systemLog: SystemLog[] | undefined;
}

export interface FileParameter {
    data: any;
    fileName: string;
}

export interface Roles {
    id: number;
    rol_Yetki_Adi: string;
}